--oracle 的dbms_application_info包
DECLARE
  L_CLINENT  VARCHAR2(100);
  L_MOD_NAME VARCHAR2(100);
  L_ACT_NAME VARCHAR2(100);
BEGIN
  DBMS_APPLICATION_INFO.SET_CLIENT_INFO('my client');
  DBMS_APPLICATION_INFO.READ_CLIENT_INFO(L_CLINENT);
  DBMS_OUTPUT.PUT_LINE('client=' || L_CLINENT);
  DBMS_APPLICATION_INFO.SET_MODULE('my mod', 'inserting');
  DBMS_APPLICATION_INFO.READ_MODULE(L_MOD_NAME, L_ACT_NAME);
  DBMS_OUTPUT.PUT_LINE('mod_name=' || L_MOD_NAME);
  DBMS_OUTPUT.PUT_LINE('act_name=' || L_ACT_NAME);
END;