--.查询用到某个表的所有对象
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_ID, STATUS
  FROM DBA_OBJECTS
 WHERE OBJECT_ID IN
       (SELECT OBJECT_ID
          FROM (SELECT OBJECT_ID, REFERENCED_OBJECT_ID
                  FROM PUBLIC_DEPENDENCY
                 WHERE REFERENCED_OBJECT_ID <> OBJECT_ID) A
        CONNECT BY PRIOR OBJECT_ID = REFERENCED_OBJECT_ID
         START WITH REFERENCED_OBJECT_ID =
                    (SELECT OBJECT_ID
                       FROM DBA_OBJECTS
                      WHERE OWNER = 'EHADMIN'
                        AND OBJECT_NAME = 'APPLICATION'
                        AND OBJECT_TYPE = 'TABLE'));