--示例3，使用VALUES OF子句：
DECLARE
  TYPE INDEX_PONITER_TYPE IS TABLE OF PLS_INTEGER;
  INDEX_PONITER INDEX_PONITER_TYPE;
  TYPE DEMO_TABLE_TYPE IS TABLE OF TMP_TAB%ROWTYPE INDEX BY BINARY_INTEGER;
  DEMO_TABLE DEMO_TABLE_TYPE;
BEGIN
  INDEX_PONITER := INDEX_PONITER_TYPE(1, 3, 5, 7);
  FOR I IN 1 .. 10 LOOP
    DEMO_TABLE(I).ID := I;
    DEMO_TABLE(I).NAME := 'NAME' || I;
  END LOOP;
  FORALL I IN VALUES OF INDEX_PONITER
    INSERT INTO TMP_TAB VALUES DEMO_TABLE (I);

  COMMIT;
END;