--示例2，使用INDICES OF子句：
DECLARE
  TYPE DEMO_TABLE_TYPE IS TABLE OF TMP_TAB%ROWTYPE INDEX BY BINARY_INTEGER;
  DEMO_TABLE DEMO_TABLE_TYPE;
BEGIN
  FOR I IN 1 .. 10 LOOP
    DEMO_TABLE(I).ID := I;
    DEMO_TABLE(I).NAME := 'NAME' || I;
  END LOOP;
  -- 使用集合的delete方法移除第3、6、9三个成员
  DEMO_TABLE.DELETE(3);
  DEMO_TABLE.DELETE(6);
  DEMO_TABLE.DELETE(9);
  FORALL I IN INDICES OF DEMO_TABLE
    INSERT INTO TMP_TAB VALUES DEMO_TABLE (I);

  COMMIT ;
END;