-- CREATE TABLE
CREATE TABLE EMP_TEST(
  EMPNO NUMBER(5),
  ENAME VARCHAR2(50),
  HIREDATE DATE,
  SAL NUMBER(5),
  DEPTNO NUMBER(4)
);

--INIT TEST DATA
--使用FORALL批量插入、修改、删除数据：
--批量插入
DECLARE
  -- 定义索引表类型
  TYPE TB_TABLE_TYPE IS TABLE OF EMP_TEST%ROWTYPE INDEX BY BINARY_INTEGER;
  TB_TABLE TB_TABLE_TYPE;
BEGIN
  FOR I IN 1 .. 100 LOOP
    TB_TABLE(I).EMPNO := I;
    TB_TABLE(I).ENAME := 'NAME' || I;
    TB_TABLE(I).HIREDATE := SYSDATE;
    TB_TABLE(I).SAL := I*10 + 200;
    TB_TABLE(I).DEPTNO := I*10;
  END LOOP;

  FORALL I IN 1 .. TB_TABLE.COUNT
    INSERT INTO EMP_TEST VALUES TB_TABLE (I);

  COMMIT;
END;
